// Copyright 2026 Signal Messenger, LLC
// SPDX-License-Identifier: AGPL-3.0-only

import {
  createHash,
  createHmac,
  randomBytes,
  randomInt,
  timingSafeEqual,
} from 'node:crypto';
import z from 'zod';
import { parseAuthHeader } from './util';
import { CallingPublicKey } from './sfu/crypto';

export type Uint32 = number & { Uint32: never };

const UINT32_MAX = 4_294_967_296; // 2 ** 32 − 1

function getRandomUint32(): Uint32 {
  const minInclusive = 0;
  const maxExclusive = UINT32_MAX + 1;
  return randomInt(minInclusive, maxExclusive) as Uint32;
}

export type HexString = string & { HexString: never };

export function getRandomHexString(size: number): HexString {
  return randomBytes(size).toString('hex') as HexString;
}

/**
 * Calling IDs
 * ----------------------------------------------------------------------------
 */

/**
 * In multi-participant calls, the room id is the permanent ID
 * equivalent to an ACI. It comes from a shared secret owned by the clients.
 */
export type CallingRoomId = string & { RoomId: never };

/**
 * Ephemeral, generated by calling service.
 * Only used for group/adhoc calls.
 */
export type CallingEraId = HexString & { EraId: never };

export function getRandomCallingEraId(): CallingEraId {
  return getRandomHexString(16) as CallingEraId;
}

export type CallingDemuxId = Uint32 & { DemuxId: never };

export function getRandomCallingDemuxId(): CallingDemuxId {
  return ((getRandomUint32() & ~0b1111) >>> 0) as CallingDemuxId;
}

export type CallingUserId = HexString & { UserId: never };

export enum CallType {
  Group,
  Adhoc,
}

export enum CallLinkRestrictions {
  AdminApproval,
  None,
}

/**
 * Http
 * ----------------------------------------------------------------------------
 */

export const CallingPublicKeySchema = z
  .string()
  .nonempty()
  .transform((input) => {
    return input as HexString;
  });

export function decodeCallingPublicKey(input: HexString): CallingPublicKey {
  return CallingPublicKey.fromBytes(Buffer.from(input, 'hex'));
}

export function encodeCallingPublicKey(key: CallingPublicKey): HexString {
  return Buffer.from(key.toBytes()).toString('hex') as HexString;
}

/**
 * Peek
 * ----------------------------------------------------------------------------
 */

export type CallInfoClient = Readonly<{
  demuxId: CallingDemuxId;
  opaqueUserId: CallingUserId;
}>;

export type CallInfo = Readonly<{
  eraId: CallingEraId;
  maxClients: number;
  creatorUserId: CallingUserId;
  activeClients: ReadonlyArray<CallInfoClient>;
  pendingClients: ReadonlyArray<CallInfoClient> | null;
}>;

/**
 * Errors
 * ----------------------------------------------------------------------------
 */

export enum CallingErrorCode {
  AuthError,
  CallNotFound,
  TooManyClients,
  NoPermissionToCreateCall,
  DuplicateDemuxIdDetected,
  InternalError,
}

export class CallingError extends Error {
  #code: CallingErrorCode;
  constructor(code: CallingErrorCode, message?: string) {
    super(message);
    this.#code = code;
  }
  get code(): CallingErrorCode {
    return this.#code;
  }
}

export const CallingErrorCodesToHttpStatus: Record<CallingErrorCode, number> = {
  [CallingErrorCode.AuthError]: 401,
  [CallingErrorCode.CallNotFound]: 404,
  [CallingErrorCode.TooManyClients]: 413,
  [CallingErrorCode.NoPermissionToCreateCall]: 500,
  [CallingErrorCode.DuplicateDemuxIdDetected]: 500,
  [CallingErrorCode.InternalError]: 500,
};

/**
 * Auth
 * ----------------------------------------------------------------------------
 */

export const CALLING_SERVICE_SECRET = randomBytes(32);

function parseNumberSafe(value: string): number | null {
  const trimmed = value.trim();
  if (trimmed === '') {
    return null;
  }
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) {
    return null;
  }
  return parsed;
}

export type CallingAuthToken = Readonly<{
  userId: CallingUserId;
  groupId: CallingRoomId;
  time: number;
  isAllowedToInitiateGroupCall: boolean;
  macCiphertext: string;
  macDigest: Uint8Array<ArrayBuffer>;
}>;

export function parseCallingAuthHeader(authHeader?: string): CallingAuthToken {
  const { error, password } = parseAuthHeader(authHeader);
  if (error != null) {
    throw new CallingError(CallingErrorCode.AuthError, error);
  }

  const [
    version = '',
    userIdStr = '',
    groupIdHex = '',
    timeUnixSecsStr = '',
    permissionStr = '',
    macDigestHex = '',
  ] = password.split(':');

  if (version !== '2') {
    throw new CallingError(
      CallingErrorCode.AuthError,
      'Unsupported call auth signature',
    );
  }

  const userId = userIdStr as CallingUserId;
  if (userId.length === 0) {
    throw new CallingError(CallingErrorCode.AuthError, 'Missing userId');
  }

  const groupId = Buffer.from(groupIdHex, 'hex').toString() as CallingRoomId;
  if (groupId.length === 0) {
    throw new CallingError(CallingErrorCode.AuthError, 'Missing groupId');
  }

  const timeUnixSecs = parseNumberSafe(timeUnixSecsStr);
  if (timeUnixSecs == null) {
    throw new CallingError(
      CallingErrorCode.AuthError,
      'Time not encoded correctly',
    );
  }
  const time = timeUnixSecs * 1000;

  const isAllowedToInitiateGroupCall = permissionStr === '1';

  const macDigest = Buffer.from(macDigestHex, 'hex');
  if (macDigest.length === 0) {
    throw new CallingError(CallingErrorCode.AuthError, 'Missing macDigest');
  }

  const macCiphertext = password.slice(
    0,
    password.length - macDigestHex.length - 1,
  );

  const token: CallingAuthToken = {
    userId,
    groupId,
    time,
    isAllowedToInitiateGroupCall,
    macCiphertext,
    macDigest,
  };

  return token;
}

const GV2_AUTH_MATCH_LIMIT = 10;
const GV2_AUTH_MAX_HEADER_AGE = 30 * 60 * 60 * 1000;

export type CallingAuth = Readonly<{
  userId: CallingUserId;
  roomId: CallingRoomId;
  isAllowedToInitiateGroupCall: boolean;
}>;

export function verifyCallingAuthToken(
  token: CallingAuthToken,
  key: Uint8Array<ArrayBuffer>,
): CallingAuth {
  const expectedDigest = createHmac('sha256', key)
    .update(token.macCiphertext)
    .digest()
    .subarray(0, GV2_AUTH_MATCH_LIMIT);

  if (!timingSafeEqual(expectedDigest, token.macDigest)) {
    throw new CallingError(CallingErrorCode.AuthError, 'Incorrect hmac digest');
  }

  if (Date.now() > token.time + GV2_AUTH_MAX_HEADER_AGE) {
    throw new CallingError(CallingErrorCode.AuthError, 'Expired credentials');
  }

  const auth: CallingAuth = {
    userId: token.userId,
    roomId: token.groupId,
    isAllowedToInitiateGroupCall: token.isAllowedToInitiateGroupCall,
  };

  return auth;
}

export type GenerateCallingAuthTokenOptions = Readonly<{
  userId: Uint8Array<ArrayBuffer>;
  groupId: string;
  isAllowedToInitiateGroupCall: boolean;
  key: Uint8Array<ArrayBuffer>;
}>;

export function generateCallingAuthToken(
  options: GenerateCallingAuthTokenOptions,
): string {
  let data = '';

  data += '2';
  data += ':';
  data += createHash('sha256').update(options.userId).digest('hex');
  data += ':';
  data += Buffer.from(options.groupId).toString('hex');
  data += ':';
  data += `${Math.trunc(Date.now() / 1000)}`;
  data += ':';
  data += options.isAllowedToInitiateGroupCall ? '1' : '0';

  const hmac = createHmac('sha256', options.key)
    .update(data)
    .digest()
    .subarray(0, GV2_AUTH_MATCH_LIMIT)
    .toString('hex');

  return `${data}:${hmac}`;
}
